### ISSUE TITLE
OS-X / Mac Support

### ISSUE THREAD

**Issue by AndrewFarley** [awslabs/mountpoint-s3#444]
### Tell us more about this new feature.

Tell us more about this new feature.

Support for OS-X with S3 being presented presented as a mounted drive in the Finder and available in the Terminal as you would use similarly in Linux

**Comment by dannycjones** [comment]
Thank you for the feature request, Andrew! I have no information to share about official support for macOS.

Anecdotally, I've been able to run Mountpoint during development and interact with files both from a terminal as well as in Finder. It does require there to be FUSE support from the macOS kernel, which you may be able to provide using something like [macFUSE](https://osxfuse.github.io/). However, this is not something we officially support or recommend at this time.

**Comment by mojodna** [comment]
I'm unable to install macFUSE due to the kernel extension requirement. However, I was able to build `mountpoint-s3` against [`fuse-t`](https://www.fuse-t.org/), a kext-less FUSE implementation, after applying the following patch. Unfortunately, while it runs (and debug logging indicates that mounting was successful) and even triggers the `fuse-t`'s NFS mount, it doesn't show up in the list of volumes (`df -h`) and the target path appears empty. ([The `fuse-t` version of `sshfs`](https://github.com/macos-fuse-t/sshfs) _does_ work, fwiw.)

```console
❯ ps ax | grep nfs
24545   ??  Ss     0:00.02 /usr/local/bin/go-nfsv4 -r --noatime=true /tmp/s3
```

```patch
diff --git i/vendor/fuser/build.rs w/vendor/fuser/build.rs
index 8a1dc97..8f39a57 100644
--- i/vendor/fuser/build.rs
+++ w/vendor/fuser/build.rs
@@ -13,11 +13,18 @@ fn main() {
                 .is_ok()
             {
                 println!("cargo:rustc-cfg=feature=\"libfuse2\"");
-            } else {
-                pkg_config::Config::new()
+            } else if pkg_config::Config::new()
                     .atleast_version("2.6.0")
                     .probe("osxfuse") // for osxfuse 3.x
                     .map_err(|e| eprintln!("{}", e))
+                    .is_ok()
+            {
+                println!("cargo:rustc-cfg=feature=\"libfuse2\"");
+            } else {
+                pkg_config::Config::new()
+                    .atleast_version("1.0.27")
+                    .probe("fuse-t") // for fuse-t (https://github.com/macos-fuse-t/fuse-t)
+                    .map_err(|e| eprintln!("{}", e))
                     .unwrap();
                 println!("cargo:rustc-cfg=feature=\"libfuse2\"");
             }
```

**Comment by macos-fuse-t** [comment]
@mojodna 
Clone and build libfuse from https://github.com/macos-fuse-t/libfuse. 
Then build https://github.com/macos-fuse-t/libfuse/mountpoint-s3.git

**Comment by cpboyd** [comment]
@macos-fuse-t I think you meant https://github.com/macos-fuse-t/mountpoint-s3
Took a bit for me to find it

**Comment by mojodna** [comment]
@macos-fuse-t whoa, that's awesome. working like a charm! thanks for writing the patch!

**Comment by AugustDev** [comment]
@macos-fuse-t @mojodna  @cpboyd can you explain in bit more detail how you managed to build mountpoint-s3 on Mac?

**Comment by WesleyBatista** [comment]
@AugustDev, here are the steps I've followed on a M1:
1. Install macFUSE - a bit tricky as it requires you to enable Kernel Extensions. Installation windows will instruct you
2. `git clone git@github.com:awslabs/mountpoint-s3.git --recurse-submodules` - it got a bit slow cloning  `mountpoint-s3-crt-sys/crt/s2n-tls` submodule...
3. finally, cd into cloned directory and run `cargo run --release`

<img width="464" alt="Screenshot 2024-01-01 at 14 15 20" src="https://github.com/awslabs/mountpoint-s3/assets/755254/a539c812-8b8f-48bd-a38f-ccbf8f276809">

**Comment by AugustDev** [comment]
Thanks for the comment @WesleyBatista. I'm trying to build on M1 and following your steps I get an error 

```
   Compiling bytes v1.6.0
   Compiling bincode v1.3.3
   Compiling mountpoint-s3-crt v0.7.0 (/Users/wpc/Projects/cfdx/mountpoint-s3/mountpoint-s3-crt)
   Compiling mountpoint-s3-client v0.8.1 (/Users/wpc/Projects/cfdx/mountpoint-s3/mountpoint-s3-client)
   Compiling mountpoint-s3 v1.6.0 (/Users/wpc/Projects/cfdx/mountpoint-s3/mountpoint-s3)
error[E0658]: use of unstable library feature 'result_option_inspect'
    --> mountpoint-s3/src/inode.rs:1592:37
     |
1592 |         self.map.insert(ino, inode).inspect(Self::remove_metrics)
     |                                     ^^^^^^^
     |
     = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information

error[E0658]: use of unstable library feature 'result_option_inspect'
    --> mountpoint-s3/src/inode.rs:1596:30
     |
1596 |         self.map.remove(ino).inspect(Self::remove_metrics)
     |                              ^^^^^^^
     |
     = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `mountpoint-s3` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by passaro** [comment]
@AugustDev, are you building with the latest stable toolchain?
On macOS, that's currently:
```
$ rustup show
[..]
stable-aarch64-apple-darwin (default)
rustc 1.78.0 (9b00956e5 2024-04-29)
```

**Comment by falozzo** [comment]
Hi, I'm struggling with this error when I try to build mountpoint-s3 with `cargo build --release`:

` make: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  thread 'main' panicked at /Users/a406769/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.63/src/fallback.rs:791:9:
  "aws_io_handle_union_(unnamed_at_/Users/a406769/dev/tools/mountpoint-s3/target/release/build/mountpoint-s3-crt-sys-973e00d705cecc49/out/target/include/aws/io/io_h_18_5)" is not a valid Ident
 `

Any ideas?

Thanks in advance

**Comment by falozzo** [comment]
> Hi, I'm struggling with this error when I try to build mountpoint-s3 with `cargo build --release`:
> 
> ```
>  make: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
>   thread 'main' panicked at /Users/a406769/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.63/src/fallback.rs:791:9:
>   "aws_io_handle_union_(unnamed_at_/Users/a406769/dev/tools/mountpoint-s3/target/release/build/mountpoint-s3-crt-sys-973e00d705cecc49/out/target/include/aws/io/io_h_18_5)" is not a valid Ident
> ```
> 
> ```
> $ rustup show
> Default host: x86_64-apple-darwin
> rustup home:  /Users/a406769/.rustup
> stable-x86_64-apple-darwin (default)
> rustc 1.78.0 (9b00956e5 2024-04-29)
> ```
> 
> Any ideas?
> 
> Thanks in advance

I solved cloning the original repo as @AugustDev previously said. Thanks

> @AugustDev, here are the steps I've followed on a M1:
> 
> 1. Install macFUSE - a bit tricky as it requires you to enable Kernel Extensions. Installation windows will instruct you
> 2. `git clone git@github.com:awslabs/mountpoint-s3.git --recurse-submodules` - it got a bit slow cloning  `mountpoint-s3-crt-sys/crt/s2n-tls` submodule...
> 3. finally, cd into cloned directory and run `cargo run --release`
> 
> <img alt="Screenshot 2024-01-01 at 14 15 20" width="464" src="https://private-user-images.githubusercontent.com/755254/293587810-a539c812-8b8f-48bd-a38f-ccbf8f276809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTgwMTgsIm5iZiI6MTcxODE5NzcxOCwicGF0aCI6Ii83NTUyNTQvMjkzNTg3ODEwLWE1MzljODEyLThiOGYtNDhiZC1hMzhmLWNjYmY4ZjI3NjgwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxMzA4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWIyMDY5YjljNDVlYTJmNmE0ZTcyYWY3ZTU3MzFiNmI3ZmVjZjY4Y2ViMjM3MjEwNzRkMjM0YjhhNjliZWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HQ-koSnb2vF0b5gF8R9z6R4lhZY7d9JVS32ryxd3UT8">

**Comment by max-lobur** [comment]
I have success running mountpoint-s3 inside docker container on apple silicon mac, and then simply re-sharing that dir with mac via NFS from same container. Works read-write, no extra dependencies needed
